### ISSUE TITLE
PSR-12

### ISSUE THREAD

**Issue by domioedition** [alexanderzenchenko/phplab-tasks#1]
https://github.com/alexanderzenchenko/phplab-tasks/blob/45d5b31a3fc8b006461b99675e3a5cf8341798ef/src/01-basics.php#L15

https://www.php-fig.org/psr/psr-12/#51-if-elseif-else
1) По рекомендациям PSR необходимо добавлять фигурные скобки в if, elseif, else.
3) Я бы добавил еще проверку на отрицательное значение чтоб поиск был в зиапазоне только от 0 до 60.

4) isLeapYear в описании функции есть ссылка на Вики(https://en.wikipedia.org/wiki/Leap_year) и там расписан алгоритм вычисления високосного года.
7) Как еще можно решить эту задачу (подсказка function date)

8) isSumEqual а как решить без функций для массивов?

**Comment by alexanderzenchenko** [comment]
4.
```
function isLeapYear(int $year)
{
    if ($year < 1900) {
        throw new InvalidArgumentException();
    }

    return (bool) date("L", mktime(0, 0, 0, 1, 1, $year));
}
```
5. Можно просуммировать, обращаясь к символам в строке:
`return $input[0] + $input[1] + $input[2] === $input[3] + $input[4] + $input[5]`

**Comment by domioedition** [comment]
Great job!
